### ISSUE TITLE
README is broken

### ISSUE THREAD

**Issue by KaKi87** [cyrildever/feistel-cipher#12]
Hi,

The README is broken :

![](https://github.com/cyrildever/feistel-cipher/assets/21284089/991dcd28-33da-475b-a341-c6027c9d2111)

Thanks

**Comment by cyrildever** [comment]
This is fixed (for Github at least).

_NB: Latex in Markdown doesn't seem to work on the NPM website, but it's less awful with the `$` sign than with the broken link._
